// AUTO-GENERATED FILE — Do not edit manually
// Generated by astro-src/scripts/generate-paths.mjs
// Generated at: 2026-09-09T17:18:54.007Z

export const ideasPaths = ['agent-planning-reasoning', 'context-window-extension', 'contrastive-sentence-embeddings', 'efficient-context-retrieval', 'evaluation-benchmark-robustness', 'multimodal-chain-of-thought', 'multimodal-safety-alignment', 'rag-system-optimization', 'rlhf-preference-model-analysis', 'test-new-idea', 'transformer-attention-scaling'] as const;
export const experimentsPaths = ['ablation-llm-scale', 'benchmark-prompt-sensitivity', 'hyperparameter-learning-rate-llm', 'model-comparison-gpt4o-vs-sonnet', 'multimodal-cot-prompting', 'preference-model-generalization', 'prompt-engineering-chain-of-thought', 'user-study-rag-accuracy'] as const;
export const writingPaths = ['multimodal-cot-analysis', 'multimodal-efficiency-proposal', 'reward-model-generalization-report', 'scaling-laws-workshop', 'transformer-attention-explained'] as const;
export const roadmapPaths = ['industry-llm-agent-2026', 'llm-alignment-research-2026', 'phd-marl-2026'] as const;

export const allModulePaths = {
  ideasPaths: ideasPaths,
  experimentsPaths: experimentsPaths,
  writingPaths: writingPaths,
  roadmapPaths: roadmapPaths,
} as const;

export type ModuleName = keyof typeof allModulePaths;
