#!/usr/bin/env node
// astro-src/scripts/generate-paths.mjs
//
// Scans docs/{module}/*.md files and generates TypeScript with path arrays.
// Output: astro-src/lib/paths.generated.ts
//
// Run: node astro-src/scripts/generate-paths.mjs

import { readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = process.cwd();
const DOCS_DIR = join(ROOT, 'docs');
const OUT_FILE = join(ROOT, 'astro-src', 'lib', 'paths.generated.ts');

// Modules to scan (maps directory name to path array variable name)
const MODULES = [
  { dir: 'ideas', var: 'ideasPaths' },
  { dir: 'experiments', var: 'experimentsPaths' },
  { dir: 'writing', var: 'writingPaths' },
  { dir: 'roadmap', var: 'roadmapPaths' },
];

function scanModule(moduleDir) {
  const modulePath = join(DOCS_DIR, moduleDir);
  if (!existsSync(modulePath)) {
    console.log(`[generate-paths] ${moduleDir}/ not found, skipping`);
    return [];
  }

  const files = readdirSync(modulePath, { withFileTypes: true });
  const ids = [];

  for (const f of files) {
    if (f.isFile() && f.name.endsWith('.md')) {
      // Strip .md extension to get the ID
      const id = f.name.replace(/\.md$/, '');
      ids.push(id);
    }
  }

  // Sort for consistent output
  ids.sort();

  console.log(`[generate-paths] ${moduleDir}: ${ids.length} paths`);
  return ids;
}

function generateTypeScript(pathsByModule) {
  const lines = [
    '// AUTO-GENERATED FILE — Do not edit manually',
    '// Generated by astro-src/scripts/generate-paths.mjs',
    `// Generated at: ${new Date().toISOString()}`,
    '',
  ];

  // Generate individual path arrays
  for (const [varName, paths] of Object.entries(pathsByModule)) {
    if (paths.length > 0) {
      const quoted = paths.map(p => `'${p}'`).join(', ');
      lines.push(`export const ${varName} = [${quoted}] as const;`);
    }
  }

  lines.push('');

  // Generate allModulePaths object
  const keys = Object.keys(pathsByModule).filter(k => pathsByModule[k].length > 0);
  if (keys.length > 0) {
    lines.push('export const allModulePaths = {');
    for (const key of keys) {
      lines.push(`  ${key}: ${key},`);
    }
    lines.push('} as const;');
  }

  lines.push('');

  // Helper type
  lines.push('export type ModuleName = keyof typeof allModulePaths;');

  return lines.join('\n') + '\n';
}

function main() {
  console.log('[generate-paths] Starting...');

  const pathsByModule = {};

  for (const mod of MODULES) {
    const paths = scanModule(mod.dir);
    pathsByModule[mod.var] = paths;
  }

  const total = Object.values(pathsByModule).reduce((sum, arr) => sum + arr.length, 0);
  console.log(`[generate-paths] Total: ${total} paths across ${MODULES.length} modules`);

  const tsContent = generateTypeScript(pathsByModule);
  writeFileSync(OUT_FILE, tsContent, 'utf-8');

  console.log(`[generate-paths] Written to: ${OUT_FILE}`);
}

main();
